<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>UI\Icons\Skill-Forge-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="UI\Icons\Skill-Forge-icon.ico" />
    <None Remove="UI\Images\icons8-add-user-100.png" />
    <None Remove="UI\Images\icons8-course-page-100.png" />
    <None Remove="UI\Images\icons8-courses-48.png" />
    <None Remove="UI\Images\icons8-edit-48.png" />
    <None Remove="UI\Images\icons8-folder-96.png" />
    <None Remove="UI\Images\icons8-green-information-64.png" />
    <None Remove="UI\Images\icons8-my-course-page-100.png" />
    <None Remove="UI\Images\icons8-open-door-96.png" />
    <None Remove="UI\Images\icons8-plus-50.png" />
    <None Remove="UI\Images\icons8-profile-96.png" />
    <None Remove="UI\Images\icons8-user-60.png" />
    <None Remove="UI\Images\icons8-users-page-100.png" />
    <None Remove="UI\Images\icons8-workshop-100.png" />
    <None Remove="UI\Images\icons8-workshop-96.png" />
    <None Remove="UI\Images\Skill-Forge-icon.png" />
    <None Remove="UI\Shaders\DeeperColorEffect.ps" />
    <None Remove="UI\VideoResouses\StartedScreen.mp4" />
    <None Remove="View\RegisterPage.xaml~RF531a71d.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="UI\Icons\Skill-Forge-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CredentialManagement" Version="1.0.2" />
    <PackageReference Include="libphonenumber-csharp" Version="9.0.24" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UI\Icons\Skill-Forge-icon.ico" />
    <Resource Include="UI\Images\icons8-add-user-100.png" />
    <Resource Include="UI\Images\icons8-course-page-100.png" />
    <Resource Include="UI\Images\icons8-edit-48.png" />
    <Resource Include="UI\Images\icons8-folder-96.png" />
    <Resource Include="UI\Images\icons8-green-information-64.png" />
    <Resource Include="UI\Images\icons8-my-course-page-100.png" />
    <Resource Include="UI\Images\icons8-profile-page-100.png" />
    <Resource Include="UI\Images\icons8-courses-48.png" />
    <Resource Include="UI\Images\icons8-open-door-96.png" />
    <Resource Include="UI\Images\icons8-add-user-64.png" />
    <Resource Include="UI\Images\icons8-lock-60.png" />
    <Resource Include="UI\Images\icons8-key-64.png" />
    <Resource Include="UI\Images\icons8-pass-96.png" />
    <Resource Include="UI\Images\icons8-mail-96.png" />
    <Resource Include="UI\Images\icons8-plus-50.png" />
    <Resource Include="UI\Images\icons8-profile-96.png" />
    <Resource Include="UI\Images\icons8-telephone-100.png" />
    <Resource Include="UI\Images\icons8-user-60.png" />
    <Resource Include="UI\Images\icons8-users-page-100.png" />
    <Resource Include="UI\Images\icons8-workshop-100.png" />
    <Resource Include="UI\Images\icons8-workshop-96.png" />
    <Resource Include="UI\Images\icons8-logout-64.png" />
    <Resource Include="UI\Images\icons8-sad-smile-100.png" />
    <Resource Include="UI\Images\Skill-Forge-icon.png" />
    <Resource Include="UI\Shaders\DeeperColorEffect.ps" />
    <Content Include="UI\VideoResouses\StartedScreen.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
